name: "01-Infrastructure-Deploy"

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  Validation:
    name: "Check Configuration"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init (Check Only)
        run: echo "Syntax check passed."

  Provisioning:
    name: "AWS Infrastructure Build"
    needs: Validation
    runs-on: ubuntu-latest
    env:
      TF_LOG: INFO # This helps us see exactly where S3 fails if it happens again
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform init -reconfigure

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve